name: Deploy to GitHub Pages

# Trigger on push to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Copy CNAME file
        run: |
          if [ -f CNAME ]; then
            cp CNAME dist/
            echo "CNAME file copied to dist directory"
          else
            echo "CNAME file not found in the root directory, skipping copy."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

